source 'https://rubygems.org'
ruby '1.9.3'
gem 'sinatra'
gem 'net-ldap'
# gem 'activerecord', '~>3.2.13'
gem 'activesupport'
# gem 'sqlite3'
gem 'sinatra-cas-client', :git=>'https://github.com/sioctal/sinatra-cas-client.git'